# Generated by Django 4.2.20 on 2025-03-25 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyPocket', '0008_expense_description_alter_account_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='expense_list',
            new_name='expenses',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, null=True),
        ),
    ]
